# Generated by Django 4.2.5 on 2023-10-01 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Saqlash manbaalari')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_savings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kirim manbaalari')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_income', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='chiqim manbaalari')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_expence', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
