# Generated by Django 4.2.5 on 2023-10-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_ex_sav', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='expence_name',
            new_name='savings_name',
        ),
    ]
